### ISSUE TITLE
Compiling instructions...

### ISSUE THREAD

**Issue by Jleeblanch** [MotorolaMobilityLLC/motorola-kernel-modules#1]
Hey @charleseb 

As the modules in this repo are needed for certain features to work on devices like Lake, River, Ocean, etc I would like to know how they need to be setup so they can be built (or included in the kernel?). 

Also, how do we know which modules (if not all) need to be included/built for certain devices like Lake, River, Ocean, etc. 

If you could provide some guidance on how these are to be compiled, I would greatly appreciate it!

Thank you,
Joshua

**Comment by wh0dat** [comment]
@awheeler-mmi @charleseb I also am needing these instructions as I have looked all over MotorolaMobilityLLC git searching and cannot find anything.

Please help us ??

Thanks in advance!
God Bless!
~Barry Allen

**Comment by charleseb** [comment]
Readme and dtc uptated to MMI-PPO29.114-30:
https://github.com/MotorolaMobilityLLC/readme/tree/master/dtc_MMI-PPO29.114-30
https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-PPO29.114-30.txt
