### ISSUE TITLE
Compiling instructions

### ISSUE THREAD

**Issue by wh0dat** [MotorolaMobilityLLC/motorola-kernel-modules#2]
@awheeler-mmi @charleseb I also am needing these instructions for River + Ocean (pie-9.0.0-release-ppo29 / ppo29.113-134) as I have looked all over MotorolaMobilityLLC git searching and cannot find anything.

Maybe link a commit that merges it into kernel ?

Seems its missing alot of stuff for audio.. 
Where is the source that motorola uses to compile these ???
vendor/lib/modules/audio_adsp_loader.ko
vendor/lib/modules/audio_analog_cdc.ko
vendor/lib/modules/audio_apr.ko
vendor/lib/modules/audio_cpe_lsm.ko
vendor/lib/modules/audio_digital_cdc.ko
vendor/lib/modules/audio_hdmi.ko
vendor/lib/modules/audio_machine_ext_sdm450.ko
vendor/lib/modules/audio_machine_sdm450.ko
vendor/lib/modules/audio_mbhc.ko
vendor/lib/modules/audio_native.ko
vendor/lib/modules/audio_pinctrl_wcd.ko
vendor/lib/modules/audio_platform.ko
vendor/lib/modules/audio_q6.ko
vendor/lib/modules/audio_q6_notifier.ko
vendor/lib/modules/audio_stub.ko
vendor/lib/modules/audio_swr_ctrl.ko
vendor/lib/modules/audio_swr.ko
vendor/lib/modules/audio_usf.ko
vendor/lib/modules/audio_wcd9335.ko
vendor/lib/modules/audio_wcd9xxx.ko
vendor/lib/modules/audio_wcd_core.ko
vendor/lib/modules/audio_wcd_cpe.ko
vendor/lib/modules/audio_wsa881x_analog.k
vendor/lib/modules/audio_wsa881x.ko

Not in this repo nor in kernels
Please help ??

Thanks in advance!
God Bless!
~Barry Allen

**Comment by charleseb** [comment]
Please refer to the tag instead of branches:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPO29.114-30

Readme and dtc uptated to MMI-PPO29.114-30:
https://github.com/MotorolaMobilityLLC/readme/tree/master/dtc_MMI-PPO29.114-30
https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-PPO29.114-30.txt
