### ISSUE TITLE
HELLO MOTO??

### ISSUE THREAD

**Issue by wh0dat** [MotorolaMobilityLLC/motorola-kernel-modules#3]
Please provide a proper motorola-kernel-modules and kernel including techpack for river and ocean ppo29.114-134-2

  CC      sound/soc/codecs/tfa98xx.o
/1/android/build/aexp/kernel/motorola/msm8953/sound/soc/codecs/tfa98xx.c:2944:3: error: statement requires expression of integer type ('struct snd_kcontrol_new *' invalid)
                switch(tfa98xx_controls);
                ^      ~~~~~~~~~~~~~~~~
1 error generated.
make[4]: *** [/1/android/build/aexp/kernel/motorola/msm8953/scripts/Makefile.build:339: sound/soc/codecs/tfa98xx.o] Error 1
make[3]: *** [/1/android/build/aexp/kernel/motorola/msm8953/scripts/Makefile.build:653: sound/soc/codecs] Error 2
make[2]: *** [/1/android/build/aexp/kernel/motorola/msm8953/scripts/Makefile.build:653: sound/soc] Error 2
make[1]: *** [/1/android/build/aexp/kernel/motorola/msm8953/Makefile:1090: sound] Error 2
make[1]: *** Waiting for unfinished jobs....
-------------------------------------------------------------------------
  LD [M]  /home/foxy/.../working/motorola/kernel/modules/sound/soc/codecs/tas2560_calib.o
/home/foxy/.../working/motorola/kernel/modules/sound/soc/codecs/tfa_container.c:17:22: fatal error: dbgprint.h: No such file or directory
 #include "dbgprint.h"
                      ^
compilation terminated.
make[2]: *** [/nvme/home/foxy/.../working/kernel/msm-4.9/scripts/Makefile.build:339: /home/foxy/.../working/motorola/kernel/modules/sound/soc/codecs/tfa_container.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/foxy/.../working/motorola/kernel/modules/sound/soc/codecs/tfa_dsp.c:17:22: fatal error: dbgprint.h: No such file or directory
 #include "dbgprint.h"
                      ^
compilation terminated.
make[2]: *** [/nvme/home/foxy/.../working/kernel/msm-4.9/scripts/Makefile.build:339: /home/foxy/.../working/motorola/kernel/modules/sound/soc/codecs/tfa_dsp.o] Error 1
/home/foxy/.../working/motorola/kernel/modules/sound/soc/codecs/tfa_init.c:17:22: fatal error: dbgprint.h: No such file or directory
 #include "dbgprint.h"
                      ^
compilation terminated.
make[2]: *** [/nvme/home/foxy/.../working/kernel/msm-4.9/scripts/Makefile.build:339: /home/foxy/.../working/motorola/kernel/modules/sound/soc/codecs/tfa_init.o] Error 1
/home/foxy/.../working/motorola/kernel/modules/sound/soc/codecs/tfa98xx.c:34:20: fatal error: config.h: No such file or directory
 #include "config.h"
                    ^
compilation terminated.
In file included from /home/foxy/.../working/motorola/kernel/modules/sound/soc/codecs/msm-cirrus-playback.c:25:0:
/nvme/home/foxy/.../working/kernel/msm-4.9/include/sound/msm-cirrus-playback.h:17:30: fatal error: dsp/apr_audio-v2.h: No such file or directory
 #include <dsp/apr_audio-v2.h>
                              ^
compilation terminated.

None of the sound modules compile for river or ocean..
please help

THANKS

**Comment by dps-910** [comment]
did you solve this, getting same error as this https://gist.github.com/rohanpurohit/b55a9b3348459831231011c6e7c2b29c
