### ISSUE TITLE
vendor/cirrus/audio/dlkm source code request 

### ISSUE THREAD

**Issue by erfanoabdi** [MotorolaMobilityLLC/motorola-kernel-modules#5]
Hi all,
motorola G7 (river) using cirrus as audio driver, but i noticed in android 10 branch cirrus drivers moved to a separate repo (vendor/cirrus/audio) and not pushed yet.
kindly request to push this missing repo.
related change: https://github.com/MotorolaMobilityLLC/motorola-kernel-modules/commit/34f55aa21b666e636573c9fe7c07bb64a2032c01

Thanks
Abdi

**Comment by wh0dat** [comment]
:+1:

**Comment by wh0dat** [comment]
@charleseb @awheeler-mmi ?

**Comment by charleseb** [comment]
Hi @erfanoabdi,

Version released:
https://github.com/MotorolaMobilityLLC/vendor-cirrus-audio-dlkm/releases/tag/MMI-QPU30.52-16-2
