### ISSUE TITLE
ginna: Request for Q kernel modules tag

### ISSUE THREAD

**Issue by Hasaber8** [MotorolaMobilityLLC/motorola-kernel-modules#6]

**Comment by Hasaber8** [comment]
Bump @awheeler-mmi @charleseb 
Also if the kernel modules repo is same as channel and river release please let me, working on bringing ginna to 64bit base. :-)

**Comment by Hasaber8** [comment]
> Bump @awheeler-mmi @charleseb
> Also if the kernel modules repo is same as channel and river release please let me, working on bringing ginna to 64bit base. :-)

Bump @chenyt9 @awheeler-mmi @charleseb

**Comment by awheeler-mmi** [comment]
Ginna does share the system software with river and channel.  The kernel-module branch is common between these targets.

**Comment by Hasaber8** [comment]
> Ginna does share the system software with river and channel. The kernel-module branch is common between these targets.

Thanks for the prompt reply!

**Comment by chenyt9** [comment]
@Hasaber
Here is a release Version of ginna ：https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPG30.82-95
If it can meet your needs? Thanks.

**Comment by Hasaber8** [comment]
> @Hasaber
> Here is a release Version of ginna ：https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPG30.82-95
> If it can meet your needs? Thanks.

Kernel was never the problem I just wanted to double check if there are any unreleased kernel modules!

**Comment by chenyt9** [comment]
Pls refer to this tag：https://github.com/MotorolaMobilityLLC/motorola-kernel-modules/releases/tag/MMI-QPG30.82-95
Thanks.
