### ISSUE TITLE
[REQUEST] Clarification on the kernel modules 

### ISSUE THREAD

**Issue by anoraktrend** [MotorolaMobilityLLC/motorola-kernel-modules#7]
is the tag of MMI-PPBS29.73-81-5-8 the correct kernel module source for https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPB29.73-81?

**Comment by chenyt9** [comment]
Hi，@anoraktrend ，
Pls refer to this version：https://github.com/MotorolaMobilityLLC/motorola-kernel-modules/releases/tag/MMI-PPB29.73-81
Thanks.
